### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by pirc25** [pirc25/Portfolio#6]
### Portfolio desktop version.

- Added headers 
- Added headline

Issues

- I can't fix the image background-position to the headline.

**Comment by desorgui** [comment]
**You can try :**
`background-position : left 0 top 0;`
With this line in your CSS file, you'll place the image background at the left and top sides with 0 margins.

**Comment by MmakolaMC** [comment]
Great job at implementing the navbar for the desktop version and aligning the socials on the right side of the intro section, pretty neat.

Maybe check the size of the background image first and see if it is appropriate for the desktop version and after that use the background-position attribute to move it vertically and horizontally?

**Comment by pirc25** [comment]
Thanks, I resolved it using:
 background-position : left 0 top 50%;
